# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: capability.proto
# Protobuf Python Version: 5.26.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x10\x63\x61pability.proto*\xec\x02\n\nCapability\x12\x1a\n\x16\x43\x41PABILITY_UNSPECIFIED\x10\x00\x12\x1f\n\x1b\x43\x41PABILITY_CREATE_PROCESSES\x10\x01\x12\x1f\n\x1b\x43\x41PABILITY_UPDATE_PROCESSES\x10\x02\x12 \n\x1c\x43\x41PABILITY_ARCHIVE_PROCESSES\x10\x03\x12\x1f\n\x1b\x43\x41PABILITY_DELETE_PROCESSES\x10\x04\x12 \n\x1c\x43\x41PABILITY_EXECUTE_PROCESSES\x10\x05\x12 \n\x1c\x43\x41PABILITY_MONITOR_PROCESSES\x10\x06\x12 \n\x1c\x43\x41PABILITY_CREATE_REFLECTION\x10\x07\x12 \n\x1c\x43\x41PABILITY_QUERY_REFLECTIONS\x10\x08\x12\x1a\n\x16\x43\x41PABILITY_BUILD_PLANS\x10\t\x12\x19\n\x15\x43\x41PABILITY_TEST_PLANS\x10\nb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'capability_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_CAPABILITY']._serialized_start=21
  _globals['_CAPABILITY']._serialized_end=385
# @@protoc_insertion_point(module_scope)
