# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: requirement.proto
# Protobuf Python Version: 5.26.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x11requirement.proto*\xec\x01\n\x0bRequirement\x12\x1b\n\x17REQUIREMENT_UNSPECIFIED\x10\x00\x12\x15\n\x11REQUIREMENT_AGENT\x10\x01\x12\x14\n\x10REQUIREMENT_PLAN\x10\x02\x12\x17\n\x13REQUIREMENT_PROCESS\x10\x03\x12\x16\n\x12REQUIREMENT_SEARCH\x10\x04\x12\x17\n\x13REQUIREMENT_REFLECT\x10\x05\x12\x15\n\x11REQUIREMENT_LEARN\x10\x06\x12\x17\n\x13REQUIREMENT_PREDICT\x10\x07\x12\x19\n\x15REQUIREMENT_RECOMMEND\x10\x08\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'requirement_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_REQUIREMENT']._serialized_start=22
  _globals['_REQUIREMENT']._serialized_end=258
# @@protoc_insertion_point(module_scope)
